-- First, connect to your PostgreSQL instance and run this command to create the database:
-- CREATE DATABASE budget_app;

-- Then, connect to the 'budget_app' database and run the following script.
-- In psql, you would use: \c budget_app

-- -----------------------------------------------------
-- Table "users"
-- Stores user account information.
-- -----------------------------------------------------
CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL, -- Note: Passwords should always be hashed!
  name VARCHAR(100),
  income DECIMAL(12, 2),
);

-- -----------------------------------------------------
-- Table "spending_categories"
-- Stores user-defined spending categories.
-- -----------------------------------------------------
CREATE TABLE spending_categories (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  total_budget_percent DECIMAL(5, 2), -- e.g., 25.50 for 25.50%
  total_budget_number DECIMAL(12, 2), -- e.g., 500.00 for $500.00
  CONSTRAINT fk_user
    FOREIGN KEY(user_id) 
    REFERENCES users(user_id)
    ON DELETE CASCADE -- If a user is deleted, their categories are also deleted.
);

-- -----------------------------------------------------
-- Table "transactions"
-- Stores all individual spending transactions.
-- -----------------------------------------------------
CREATE TABLE transactions (
  transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  category_id INT, -- Can be NULL if the transaction is uncategorized
  item_purchased VARCHAR(255) NOT NULL,
  cost DECIMAL(10, 2) NOT NULL,
  "time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  plaid_category VARCHAR(255),
  CONSTRAINT fk_user
    FOREIGN KEY(user_id) 
    REFERENCES users(user_id)
    ON DELETE CASCADE, -- If a user is deleted, their transactions are also deleted.
  CONSTRAINT fk_category
    FOREIGN KEY(category_id) 
    REFERENCES spending_categories(category_id)
    ON DELETE SET NULL -- If a category is deleted, the transaction becomes uncategorized.
);